language: python
before_install:
  - python3.7 -m venv env
  - env/bin/pip install --upgrade pip setuptools
  - env/bin/pip install -e ".[testing]"
  - env/bin/alembic -c development.ini revision --autogenerate -m "init"
  - env/bin/alembic -c development.ini upgrade head
  - env/bin/initialize_back_end_db development.ini
  - env/bin/pserve development.ini --reload"
