language: python
before_install:
  - python -m pip install --upgrade pip && pip install -r requirements.txt
  - python3.7 -m venv env
  - pip install --upgrade 
  - pip setuptools
  - pip install -e ".[testing]"
