matrix:
  include:
    - language: android
      jdk: oraclejdk8
      sudo: false
      
      before_install: cd MobileApplication
      android:
        components:
          - platform-tools
          - tools
          - build-tools-26.0.2
          - android-23
          - android-27
          - sys-img-armeabi-v7a-android-23
          - extra-android-m2repository

      before_script:
        # Create and start emulator
        - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
 #       - emulator -avd test -no-skin -no-audio -no-window &
 #       - android-wait-for-emulator
        - adb shell input keyevent 82 &
        - rm local.properties
        - pwd

      script: chmod +x ./gradlew && ./gradlew :app:assembleDebug connectedAndroidTest

      
    - language: python
      before_install: cd back_end
      python:
      #   - "2.6"
      #   - "2.7"
      #   - "3.3"
      #   - "3.4"
      #   - "3.5"
      #   - "3.5-dev"  # 3.5 development branch
      #   - "3.6"
      #   - "3.6-dev"  # 3.6 development branch
        - "3.7-dev"  # 3.7 development branch
      # command to install dependencies
      install:
        - python3.7 -m venv env
        - pip install --upgrade pip setuptools
        - pip install -e ".[testing]"
      # command to run tests
      script:
        - pytest 


